src/Entity/Country.php
<?php

namespace App\Entity;

use App\Repository\CountryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=CountryRepository::class)
 * @ORM\Table(name="countries")
 * @UniqueEntity("code")
 */
class Country
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30, unique=true)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $full_name;

    /**
     * @ORM\Column(type="date")
     */
    private $from_date;

    /**
     * @ORM\OneToMany(targetEntity=Holiday::class, mappedBy="country", orphanRemoval=true)
     */
    private $holidays;

    public function __construct()
    {
        $this->holidays = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getFromDate(): ?\DateTimeInterface
    {
        return $this->from_date;
    }

    public function setFromDate(\DateTimeInterface $from_date): self
    {
        $this->from_date = $from_date;

        return $this;
    }

    /**
     * @return Collection|Holiday[]
     */
    public function getHolidays(): Collection
    {
        return $this->holidays;
    }

    public function addHoliday(Holiday $holiday): self
    {
        if (!$this->holidays->contains($holiday)) {
            $this->holidays[] = $holiday;
            $holiday->setCountry($this);
        }

        return $this;
    }

    public function removeHoliday(Holiday $holiday): self
    {
        if ($this->holidays->contains($holiday)) {
            $this->holidays->removeElement($holiday);
            // set the owning side to null (unless already changed)
            if ($holiday->getCountry() === $this) {
                $holiday->setCountry(null);
            }
        }

        return $this;
    }
}

src/Entity/Holiday.php
<?php

namespace App\Entity;

use App\Repository\HolidayRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=HolidayRepository::class)
 * @ORM\Table(name="holidays",
 *  uniqueConstraints={@ORM\UniqueConstraint(columns={
 *      "name", "date", "country_id"
 *  })}
 * )
 * @UniqueEntity(
 *     fields={"name", "date", "country"},
 *     message="Holiday already exists."
 * )
 */
class Holiday
{
    public const HOLIDAY_TYPE = 'public_holiday';
    public const ALL_TYPE = 'all';
    public const OBSERVANCE_TYPE = 'observance';
    public const SCHOOL_HOLIDAY_TYPE = 'school_holiday';
    public const OTHER_DAY_TYPE = 'other_day';
    public const EXTRA_WORKING_DAY_TYPE = 'extra_working_day';

    /**
     * Returns holiday type list array.
     *
     * @return array
     */
    public static function getHolidayTypeList()
    {
        return [
            self::HOLIDAY_TYPE => 'Holiday',
            self::ALL_TYPE => 'All',
            self::OBSERVANCE_TYPE => 'Observance',
            self::SCHOOL_HOLIDAY_TYPE => 'School holiday',
            self::OTHER_DAY_TYPE => 'Other day',
            self::EXTRA_WORKING_DAY_TYPE => 'Extra working day'
        ];
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $holiday_type;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class, inversedBy="holidays")
     * @ORM\JoinColumn(nullable=false)
     */
    private $country;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getHolidayType(): ?string
    {
        return $this->holiday_type;
    }

    public function getHolidayTypePrettyName(): ?string
    {
        $holiday_type = $this->getHolidayType();
        if ($holiday_type) {
            return self::getHolidayTypeList()[$holiday_type];
        } else {
            return 'No name';
        }
    }

    public function setHolidayType(string $holiday_type): self
    {
        $this->holiday_type = $holiday_type;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Controller/HolidayController.php
<?php

namespace App\Controller;

use App\Repository\CountryRepository;
use App\Service\CountryService;
use App\Service\HolidayService;
use App\Utils\HolidayUtils;
use DateTime;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class HolidayController extends AbstractController
{
    private $countryService;

    public function __construct(CountryService $countryService)
    {
        $this->countryService = $countryService;
    }


    /**
     * @Route("/holiday-search", name="holiday-search", methods={"GET","POST"})
     */
    public function search(Request $request, HolidayService $holidayService)
    {
        $countries = $this->countryService->getCountries();

        if ($request->isMethod('POST')) {
            $selectedCountry = $request->get('country');
            $selectedYear = $request->get('year');

            $holidays = $holidayService->getHolidays($selectedCountry, $selectedYear);
            $maxSeriesFreedays = $holidayService->getLongestSeriesOfFreedaysCount($selectedYear, $selectedCountry);
            $currentDayStatus = $holidayService->getDayStatus((new DateTime()), [], $selectedCountry);

            return $this->render('pages/holiday_search.html.twig', [
                'holidayMonthGroups' => HolidayUtils::groupByMonth($holidays),
                'countries' => $countries,
                'publicHolidayCount' => HolidayUtils::countPublicHolidays($holidays),
                'selectedCountry' => $selectedCountry,
                'currentDayStatus' => $currentDayStatus,
                'maxSeriesFreedays' => $maxSeriesFreedays
            ]);
        }

        return $this->render('pages/holiday_search.html.twig', [
            'countries' => $countries,
        ]);
    }

    /**
     * @Route("ajax/country-from/{countryCode}", options={"expose" = true}, name="ajax_get_country_available_from")
     */
    public function getCountryAvailableFrom(string $countryCode)
    {
        $dateFrom = $this->countryService->getCountryFromDate($countryCode);

        $statusCode = $dateFrom ? 200 : 404;
        $payload = $dateFrom ? $dateFrom : "Country not found.";

        return new JsonResponse($payload, $statusCode);
    }
}

src/Controller/PageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class PageController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        return $this->render('pages/home.html.twig');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Holiday Watcher Home{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
    </head>
    <header>{% block header %}{% endblock %}</header>
    <body>
        {% for message in app.flashes('notice') %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        <div class="page-content-wrapper">
            {% block body %}{% endblock %}
        </div>
        {% block javascripts %}
            {#Heroku can't find script in app.js#}
            <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
            <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </body>
    <footer>{% block footer %}{% endblock %}</footer>
</html>

templates/layouts/basic_layout.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ path('home') }}">Holiday Watcher</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headerNavbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse"  id="headerNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('holiday-search') }}">Search holidays</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

templates/pages/holiday_search.html.twig
{% extends 'layouts/basic_layout.html.twig' %}

{% block title %}Search page{% endblock %}

{% block body %}
<div class="holiday-search-page">
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <!-- Using a form type here would introduce unnecessary complications -->
                <form method="POST">
                    <div class="form-group">
                        <label for="countrySelect">Country</label>
                        {% if countries|length > 0 %}
                            <select class="form-control" name="country" id="countrySelect">
                                    {% for country in countries %}
                                        {% if selectedCountry is defined and country.code == selectedCountry %}
                                            <option selected="selected" value="{{ country.code }}">{{ country.fullName }}</option>
                                        {% else %}
                                            <option value="{{ country.code }}">{{ country.fullName }}</option>
                                        {% endif %}
                                    {% endfor %}
                            </select>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="yearSelect">Year</label>
                        <select class="form-control" name="year" id="yearSelect"></select>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Find holidays</button>
                </form>

                {% if holidayMonthGroups is defined %}
                    <h2>Today: {{ currentDayStatus }}</h2>
                    <h2>Total public holidays: {{ publicHolidayCount }}</h2>
                    <h2>Maximum number of free days in a row: {{ maxSeriesFreedays }}</h2>
                    <table class="table" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Country</th>
                                <th>Holiday title</th>
                                <th>Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if holidayMonthGroups|length > 0 %}  
                                {% for month, monthHolidays in holidayMonthGroups %}
                                    <tr class="month-devider"><th colspan="4">{{ month }}</th></tr>
                                    {% for holiday in monthHolidays %}
                                    <tr>
                                        <td>{{ holiday.country.fullName }}</td>
                                        <td><a href="https://www.google.com/search?q={{ holiday.name }}">{{ holiday.name }}</a></td>
                                        <td>{{ holiday.date|date("Y/m/d") }}</td>
                                        <td>{{ holiday.holidayTypePrettyName }}</td>
                                    </tr>
                                    {% endfor %}
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td>No results found.</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/home.html.twig
{% extends 'layouts/basic_layout.html.twig' %}

{% block body %}
    <div class="holiday-search-page">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <h1>Hey, welcome to holiday watcher!</h1>
                </div>
            </div>
        </div>
    </div>
{% endblock %}